### PR TITLE
Fix Dialog backdrop type

### LINKED ISSUE #1698: `styled.div` from `@emotion/styled` is type incompatible with `backdrop` option of `Dialog`
### Current behavior

Assigning a `styled.div` component from `@emotion/styled` to the `backdrop` option of `Dialog` will fail with error `ts(2769)`.

(earlier lines omitted for readability)

 > `Type 'LegacyRef<HTMLDivElement> | undefined' is not assignable to type '((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.`

 > `Type 'string' is not assignable to type '((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.`

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/ariakit-dialog-dialogoptions-backdrop-type-issue-mj9txt
2. Change Line 33 from `backdrop={BackdropFine}` to `backdrop={BackdropError}`
3. Check compile errors

### Expected behavior

Above code should compile with no type errors.

### Workaround

Supplying `ComponentPropsWithRef` as props type to `styled` every time, e.g. ``styled.div<ComponentPropsWithRef<"div">>`opacity: 0;`;`` fixes the issue.

### Possible solutions

- Changing the type of `DialogOptions.backdrop` to `boolean | ElementType<ComponentPropsWithRef<"div">> | ElementType<JSX.IntrinsicElements["div"]>` might work. (Haven't tried)
- Wait until React and libraries completely drop support for `LegacyRef`.

### Details (of why this happens)

In `ariakit/ts/dialog`, the type of `DialogOptions.backdrop` is defined as `backdrop?: boolean | ElementType<ComponentPropsWithRef<"div">>`. 
```typescript
/** ariakit/ts/dialog */
export declare type DialogOptions<T extends As = "div"> = FocusableOptions<T> & PortalOptions<T> & Omit<DisclosureContentOptions<T>, "state"> & {
    /** ... */
    backdrop?: boolean | ElementType<ComponentPropsWithRef<"div">>;
    /** ... */
}
```

This in turn is `ElementType<PropsWithRef<ComponentProps<"div">>`,
```typescript
// @types/react/index.d.ts
    /** ... */
    type ElementType<P = any> =
        {
            [K in keyof JSX.IntrinsicElements]: P extends JSX.IntrinsicElements[K] ? K : never
        }[keyof JSX.IntrinsicElements] |
        ComponentType<P>;
    /** ... */
    type PropsWithRef<P> =
        // Just "P extends { ref?: infer R }" looks sufficient, but R will infer as {} if P is {}.
        'ref' extends keyof P
            ? P extends { ref?: infer R | undefined }
                ? string extends R
                    ? PropsWithoutRef<P> & { ref?: Exclude<R, string> | undefined }
                    : P
                : P
            : P;
    /** ... */
    type ComponentProps<T extends keyof JSX.IntrinsicElements | JSXElementConstructor<any>> =
        T extends JSXElementConstructor<infer P>
            ? P
            : T extends keyof JSX.IntrinsicElements
                ? JSX.IntrinsicElements[T]
                : {};
    type ComponentPropsWithRef<T extends ElementType> =
        T extends (new (props: infer P) => Component<any, any>)
            ? PropsWithoutRef<P> & RefAttributes<InstanceType<T>>
            : PropsWithRef<ComponentProps<T>>;
    /** ... */
}
```
`JSX.IntrinsicElements["div"]` is `React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>`, which has `ref?: LegacyRef<T>` where `LegacyRef<T> = string | Ref<T>`.

```typescript
// @types/react/index.d.ts

    /** ... */
    type LegacyRef<T> = string | Ref<T>;
    /** ... */
    type DetailedHTMLProps<E extends HTMLAttributes<T>, T> = ClassAttributes<T> & E;
    /** ... */
    interface ClassAttributes<T> extends Attributes {
      ref?: LegacyRef<T> | undefined;
    }
    /** ... */
```

In the above, `PropsWithRef<P>` explicitly excludes `string` from the possible types of `ref`.
Meanwhile, `@emotion/styled` uses `JSX.IntrinsicElements["div"]` as the props type, allowing `ref` to be of `string` type.

```typescript
// @emotion/styled/types/index.d.ts
/** ... */
export type StyledTags = {
  [Tag in keyof JSX.IntrinsicElements]: CreateStyledComponent<
    {
      theme?: Theme
      as?: React.ElementType
    },
    JSX.IntrinsicElements[Tag]
  >
}

export interface CreateStyled extends BaseCreateStyled, StyledTags {}

declare const styled: CreateStyled
export default styled
/** ... */
```
This is to retain backwards compatibility to an older Ref API where DOM nodes could be assigned a string `ref` and accessed as `this.refs.some_ref_name`.

While the API is deprecated and is being phased out, not being able to directly use `styled` components is cumbersome for the moment.

### PR DESCRIPTION
**Pull request by georgekaran**
Closes #1698

This PR fixes an incorrect type in the property `backdrop`.

Currently, this type does not allow passing `forwardRef` components, but if I do not forward the ref, I get the following error from React:
image

### CODE REVIEW

**Comment by diegohaz** [comment]
Thanks for the PR, @georgekaran! Do you know if this still works with https://github.com/ariakit/ariakit/pull/1703?

cc @Heartade

**Comment by georgekaran** [comment]
> Thanks for the PR, @georgekaran! Do you know if this still works with #1703?
> 
> cc @Heartade

Yep, just tested locally, and still working as expected.

**Comment by diegohaz** [comment]
I wonder if the code on #1700 (replaced by #1703) would work for both cases.

**Comment by Heartade** [comment]
The pre-#1700, #1700 and and subsequently #1703 should all work with `React.forwardRef` AFAIK, but it is important that a Backdrop component only accepts `RefObject<HTMLDivElement>` as its `ref`. Looking at `DialogBackdrop` (at `dialog-backdrop.tsx:36`) it refers to the actual backdrop component using `useRef<HTMLDivElement>`, so it seems that the backdrop should be a `div` after all.

So while `React.forwardRef<HTMLDivElement>((props, ref)=>(...))` does work even without #1700, using `React.forwardRef((props, ref)=>(...))` or `React.forwardRef<HTMLButtonElement>((props, ref)=>(...))` for example will throw `TypeError`.

If we need to make it possible for a backdrop to be some other component or allow something else as `ref` to a backdrop, we would have to make the types generic. That sounds like a big work.

**Comment by georgekaran** [comment]
First of all, thanks so much @Heartade for a such detailed explanation, it was super insightful.

Previously I was typing my backdrop as the following:
```tsx
const AnimatedBackdrop = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
    (props, ref) => (
```

By taking a look at the internal types of React, I've changed to the following:
```tsx
const AnimatedBackdrop = forwardRef<HTMLDivElement>(
    (props: HTMLAttributes<HTMLDivElement>, ref) => (
```

This did the trick for me, so I gonna close this PR for now as it's not necessary to change anything on `Ariakit`.

**Comment by Heartade** [comment]
Glad to hear that! Thanks for the mention. 🎉

**Pull request closed without merging**
