### PR TITLE
Only set z-index on dialog backdrop if needed

### PR DESCRIPTION
**Pull request by latin-1**

### CODE REVIEW

**Comment by latin-1** [comment]
I have no idea why this test fails. 😢

**Comment by latin-1** [comment]
@diegohaz 

https://github.com/ariakit/ariakit/discussions/1335#discussioncomment-2708361

If I set z-index on backdrop but not dialog, it will be overwritten to "auto" by Ariakit.

**Comment by diegohaz** [comment]
> @diegohaz 
> 
> 
> 
> https://github.com/ariakit/ariakit/discussions/1335#discussioncomment-2708361
> 
> 
> 
> If I set z-index on backdrop but not dialog, it will be overwritten to "auto" by Ariakit.

Can't you set zIndex on the dialog instead?

**Comment by latin-1** [comment]
@diegohaz Yes I can, but set z-index on a static-positioned element seems weird. Feel free to close this PR if you don't like this workaround. I have no strong opinion on this. 😊

**Comment by diegohaz** [comment]
It would be nice if we could update the backdrop zIndex only if the dialog property has been manually set. But my concern with this change is that the backdrop zIndex will not update if the zIndex property is set on the dialog after the first render. That is, only the very first zIndex value will be taken into account.

We should probably add this to the docs. But, yeah, I think having this restriction of only setting zIndex on the dialog element, for now, has better tradeoffs.

**Pull request closed without merging**
