### PR TITLE
chore: Add `disclosure-animated` example

### PR DESCRIPTION
**Pull request by johnsonthedev**
Screen Shot 2022-01-14 at 10 19 24

~I tried to use tailwinds transition utilities but they don't have an effect. I know you customized the `tailwind.config`. Could it be that this disabled the transition & animation classes?~

### CODE REVIEW

**Comment by diegohaz** [comment]
It's okay not to use Tailwind for animations here. I think it would add specific `-tw-variables` to the `style.css` file, which is also not great for the documentation.

**Comment by Johnson444** [comment]
Don't know if this is what you expected from an animated example :) Still learning all of this :) 

I tried to test the animation but it failed. It throws that content is visible, while it's not. I guessed it's because of the timeout delay and added a sleep function, but no effect.  
 
 Here is what I did:
 
 ```tsx
 
const sleep = (ms:number) => new Promise((resolve) => setTimeout(resolve, ms))

test("show/hide on click", async () => {
  render(<Example />);
  expect(getContent()).not.toBeVisible();
  expect(getDisclosure()).toHaveAttribute("aria-expanded", "false");

  await click(getDisclosure());
  expect(getContent()).toBeVisible();
  expect(getDisclosure()).toHaveAttribute("aria-expanded", "true");

  await click(getDisclosure());
  await sleep(3000);
  //Here it throws that content is still visible
  expect(getContent()).not.toBeVisible();
  expect(getDisclosure()).toHaveAttribute("aria-expanded", "false");
});
 
 ```

**Comment by diegohaz** [comment]
> Still learning all of this :)

That's what matters! :)

> I tried to test the animation but it failed. It throws that content is visible, while it's not. I guessed it's because of the timeout delay and added a sleep function, but no effect.

I'm not sure if JSDOM supports animation, but that `sleep` won't work anyway. Look at other tests that are using `waitFor`. That's what you need.

**Comment by Johnson444** [comment]
> > Still learning all of this :)
> 
> That's what matters! :)
> 
> > I tried to test the animation but it failed. It throws that content is visible, while it's not. I guessed it's because of the timeout delay and added a sleep function, but no effect.
> 
> I'm not sure if JSDOM supports animation, but that `sleep` won't work anyway. Look at other tests that are using `waitFor`. That's what you need.

failed as well. I guess it won't be supported then 

```ts
  await click(getDisclosure());
  await waitFor(expect(getContent()).not.toBeVisible, {
    timeout: 2000,
  });
  ```

**Comment by diegohaz** [comment]
That's the case where we'll probably need e2e tests. I was thinking about adding e2e test support for examples as well (they could be `e2e.ts` files inside the example folder) using [BrowserStack](https://www.browserstack.com/), but still haven't had the time to explore this.

**Pull request closed without merging**
