### PR TITLE
Fix Combobox autoSelect with virtualized list on mobile

### LINKED ISSUE #3808: AutoSelect weird behavior in virtualized SelectCombobox during Touch Events
### Current behavior

Hi @diegohaz,

I'm encountering an issue when combining Ariakit's `SelectCombobox` with Virtua, specifically when `autoSelect="true"` is enabled. The functionality generally works well, but on mobile devices, I’ve noticed some unusual behavior.

**Steps to Reproduce:**
1. Type into the combobox input.
2. Attempt to scroll using a touch event.

**Observed Behavior:**
Scrolling becomes impossible because the focus repeatedly returns to the first auto-selected element, interrupting the scrolling action.

This issue is also present in the example with `selectRenderer`

**Screenshots:**
1. autoSelect issue
2. selectrenderer

Could you please look into this? Any guidance or fixes would be greatly appreciated.

Thank you!

### Steps to reproduce the bug

https://stackblitz.com/~/github.com/marilari88/ariakit-virtua-select-combobox

### Expected behavior

I expect to scroll through the filtered SelectItems smoothly, similar to the experience on non-touch devices.

### Workaround

https://github.com/ariakit/ariakit/issues/3808#issuecomment-2123532464

### Possible solutions

_No response_

### PR DESCRIPTION
**Pull request by diegohaz**
Closes #3808

I tried to write a test for it, but Playwright doesn't seem to support scroll on touch move yet (related: https://github.com/microsoft/playwright/issues/2903).

### CODE REVIEW

**Comment by marilari88** [comment]
Hi @diegohaz I upgraded to version 0.4.7 but I still experiencing the issue

**Comment by diegohaz** [comment]
> Hi @diegohaz I upgraded to version 0.4.7 but I still experiencing the issue

Hi! I can't reproduce it on https://ariakit.org/examples/select-combobox-virtualized. I tested it on both the Chrome simulator and a real Android device.

**Comment by marilari88** [comment]
I checked it more in-depth and it turned out that we might have more than one problem. The issue related to scrolling is resolved with your PR, but I encountered another one, as you can see in the recording:


https://github.com/ariakit/ariakit/assets/32909388/c617399e-23b4-47e5-a35e-e625441ef944



I noticed this issue on the Pixel 7 and Pixel 8. The problem occurs when typing in the combobox; the popover starts flickering and I lose some characters I type.  It seems like the autocomplete bar (above the keyboard) continuosly triggers a height recalculation, causing Ariakit to reconsider the available space for the popover.

**Comment by diegohaz** [comment]
Could you please open a separate issue for that?

**Pull request merged**
