### PR TITLE
Fix nested dialogs with an intermediate third-party dialog

### PR DESCRIPTION
**Pull request by diegohaz**
This PR introduces a new `menu-wordpress-modal` example that considers multiple scenarios of using a third-party modal/dialog component in conjunction with Ariakit Dialog-derived components such as Menu and Tooltip.

Some minor bugs have been addressed, and enhancements have been made to better accommodate some of these use cases. For a more detailed understanding, please refer to the changeset files.

Here's the unlisted example page: https://ariakit.org/examples/menu-wordpress-modal

### CODE REVIEW

**Comment by georgekaran** [comment]
Hey @diegohaz, it's been a while

I stumbled upon this PR while about to report an issue, and I'm happy to say it resolved my problem.

**Comment by diegohaz** [comment]
@georgekaran Great! However, I still believe it's valuable to open an issue. As we lack tests for that specific use case, it could potentially break again in the future.

**Comment by georgekaran** [comment]
> @georgekaran Great! However, I still believe it's valuable to open an issue. As we lack tests for that specific use case, it could potentially break again in the future.

Sure, I'll do it

**Comment by georgekaran** [comment]
Just submitted an issue https://github.com/ariakit/ariakit/issues/2867, If you think the second case should be handled in another PR, I can submit another issue.

**Pull request merged**
